SET VERIFY OFF;
SET SERVEROUTPUT ON;

--TAKE INPUT FORM USER
ACCEPT USERSHOSPITALNAME CHAR PROMPT "enter your hospital name: "
ACCEPT USERSNAME CHAR PROMPT "enter your name: "
ACCEPT USERSEMAIL CHAR PROMPT "enter your email: "
ACCEPT USERSADDRESS CHAR PROMPT "enter your address: "
ACCEPT USERSPHONENUMBER NUMBER PROMPT "enter your phone number: "
ACCEPT USERBLOODGROUP CHAR PROMPT "enter your Blood group: "
  
--TRIGGER CREATE
CREATE OR REPLACE TRIGGER patienttri
BEFORE INSERT 
ON PATIENTINFOTABLE
DECLARE
BEGIN
	DBMS_OUTPUT.PUT_LINE('TRIGGER CREATED AND UPDATE DATA INTO PATIENT TABLE');
END;
/
  
DECLARE

A JOINTABLE.HospitalName%TYPE;
B PATIENTINFOTABLE.PatientName%TYPE;
C PATIENTINFOTABLE.PatientEmail%TYPE;
D PATIENTINFOTABLE.Address%TYPE;
E PATIENTINFOTABLE.PhoneNumber%TYPE;
F PATIENTINFOTABLE.BloodGroup%TYPE;

TOTALID NUMBER;
HOS_ID  ADMINTABLE.HospitalId%TYPE;
NEW_PID NUMBER;
HOS_NAME JOINTABLE.HospitalName%TYPE;
ICUNUMBER NUMBER;
S VARCHAR2(10);
ICUNOTAVAIABLE EXCEPTION;
NOHOSPITAL EXCEPTION;
BEGIN

A:= '&USERSHOSPITALNAME';
B:='&USERSNAME';
C:= '&USERSEMAIL';
D:= '&USERSADDRESS';
E:= &USERSPHONENUMBER;
F:= '&USERBLOODGROUP';

FOR R IN (SELECT * FROM JOINTABLE) LOOP

	IF R.HospitalName ~= A THEN 
		RAISE NOHOSPITAL;
		EXIT;
	END IF;
	
	IF R.HospitalName = A  AND R.IcuBedCapacity >1 THEN
		 S:='YES';
		 HOS_ID := R.HospitalId;
		 ICUNUMBER:=R.IcuBedCapacity;
		 ICUNUMBER:=ICUNUMBER-1;
		 
		 SELECT COUNT(*) INTO  TOTALID FROM PATIENTINFOTABLE;
		 NEW_PID:=TOTALID+1;
		 
		 INSERT INTO PATIENTINFOTABLE VALUES(NEW_PID,B,C,D,E,HOS_ID, SYSDATE,F,S);
		 UPDATE HOSPITALINFOTABLE@site2 SET HOSPITALINFOTABLE.IcuBedCapacity=ICUNUMBER WHERE HOSPITALINFOTABLE.HospitalId=HOS_ID  ;

		 DBMS_OUTPUT.PUT_LINE('--------SElECTED HOSPITAL NAME' ||R.HospitalName||'---------');
		 DBMS_OUTPUT.PUT_LINE('DATA INSERT SUCCESSFULLY');
		 EXIT;
	END IF;
	
	IF R.HospitalName = A  and R.IcuBedCapacity < 1 THEN
			RAISE ICUNOTAVAIABLE;
			EXIT;
	END IF;
END LOOP;

--EXECPTION RAISE 
EXCEPTION
WHEN ICUNOTAVAIABLE THEN
	DBMS_OUTPUT.PUT_LINE('NO ICU AVAIABLE IN THIS HOSPITAL AND EXCEPTION RAISE' );

WHEN NOHOSPITAL  THEN
	DBMS_OUTPUT.PUT_LINE('ENTER A VALID HOSPITAL' );
END;
/
COMMIT;