SET VERIFY OFF;
SET SERVEROUTPUT ON;

--TAKE INPUT FORM USER

ACCEPT USERSNAME CHAR PROMPT "enter your name :"
ACCEPT USERSEMAIL CHAR PROMPT "enter your email :"
 
DECLARE

B PATIENTINFOTABLE.PatientName%TYPE;
C PATIENTINFOTABLE.PatientEmail%TYPE;

CHECKNUMBER NUMBER;
HOS_ID  ADMINTABLE.HospitalId%TYPE;
NEW_PID NUMBER;
HOS_NAME JOINTABLE.HospitalName%TYPE;
ICUNUMBER NUMBER;
BLOOD VARCHAR2(10);
DATANOTFOUND EXCEPTION;

BEGIN

B:='&USERSNAME';
C:= '&USERSEMAIL';

CHECKNUMBER:=0;
FOR R IN (SELECT * FROM PATIENTINFOTABLE) LOOP
	IF R.PatientName=B  AND R.PatientEmail=C THEN
		CHECKNUMBER:=1;
		BLOOD:=R.BloodGroup;
		DBMS_OUTPUT.PUT_LINE('------------DATA FOR PATIENT ID: ' || R.PatientId ||'-----------' );
		DBMS_OUTPUT.PUT_LINE('NAME: ' || B );
		DBMS_OUTPUT.PUT_LINE('EMAIL: '|| C );
		DBMS_OUTPUT.PUT_LINE('ADDRESS: '|| R.Address);
		DBMS_OUTPUT.PUT_LINE('PHONE: ' || R.PhoneNumber);
		DBMS_OUTPUT.PUT_LINE('BLOOD: ' || R.BloodGroup);
		DBMS_OUTPUT.PUT_LINE('STATUS: ' ||R.ADMITTEDSTATUS);
		
		SELECT JOINTABLE.HospitalName INTO HOS_NAME  from JOINTABLE where JOINTABLE.HospitalId =R.HospitalId;
	    DBMS_OUTPUT.PUT_LINE(' HOSPITALNAME : ' || HOS_NAME);
		DBMS_OUTPUT.PUT_LINE('_');
	    EXIT;
	END IF;
END LOOP;
	IF  CHECKNUMBER=0 
		THEN RAISE DATANOTFOUND;
	  
	END IF;
	DBMS_OUTPUT.PUT_LINE('--------------EMERGENCY BLOOD-----------------');
FOR R IN (SELECT * FROM BLOODINFOTABLE@site2) LOOP
	IF R.BloodGroup = BLOOD THEN
	DBMS_OUTPUT.PUT_LINE('_');
	DBMS_OUTPUT.PUT_LINE('NAME: ' || R.DonerName);
	DBMS_OUTPUT.PUT_LINE('Contact: ' || R.PhoneNumber);
	DBMS_OUTPUT.PUT_LINE('Location: ' || R.Location);
	DBMS_OUTPUT.PUT_LINE('Available: ' || R.AvailableStatus);
	
	END IF;
END LOOP;
 
--EXECPTION RAISE 
EXCEPTION
WHEN DATANOTFOUND THEN
	DBMS_OUTPUT.PUT_LINE('NO DATA FOUND AND  EXCEPTION RAISE' );

END;
/
COMMIT;