--PATIENT INFORMATION TABLE
CLEAR SCREEN;
SET VERIFY OFF;
DROP TABLE PATIENTINFOTABLE;

CREATE TABLE PATIENTINFOTABLE(
PatientId number unique,
PatientName varchar2(11) ,
PatientEmail varchar2(20) unique,
Address varchar2(10) ,
PhoneNumber number ,
HospitalId number,
ADMITTED date,
BloodGroup varchar2(10),
ADMITTEDSTATUS VARCHAR2(15)
);

INSERT INTO PATIENTINFOTABLE VALUES(1,'Easinur','Easinur@gmail.com','Jatrabari',01521431446,1,SYSDATE,'O+','YES');
INSERT INTO PATIENTINFOTABLE VALUES(2,'Rashid','Rashid@gmail.com','Kadamtali',01521431446,1,SYSDATE,'O+','YES');
INSERT INTO PATIENTINFOTABLE VALUES(3,'Prantick','Prantick@gmail.com','Shaniakhra',01521431446,1,SYSDATE,'O+','YES');
INSERT INTO PATIENTINFOTABLE VALUES(4,'Israt','Israt@gmail.com','Rayerbag',01521431446,2,SYSDATE,'B+','YES');
INSERT INTO PATIENTINFOTABLE VALUES(5,'Jahan','Jahan@gmail.com','Merajnagar',01521431446,2,SYSDATE,'B+','YES');
INSERT INTO PATIENTINFOTABLE VALUES(6,'han','han@gmail.com','nagar',01521431446,2,SYSDATE,'A+','YES');
INSERT INTO PATIENTINFOTABLE VALUES(7,'Harun','Harun@gmail.com','Gulshan',01521431446,2,SYSDATE,'O+','YES');
INSERT INTO PATIENTINFOTABLE VALUES(8,'Noor','Noor@gmail.com','Mirpur',01521431446,3,SYSDATE,'O+','YES');
INSERT INTO PATIENTINFOTABLE VALUES(9,'Jannath','Jannath@gmail.com','Mirpur',01521431446,3,SYSDATE,'AB+','YES');


SELECT * FROM PATIENTINFOTABLE;
COMMIT;

